version: '2'
services:
  web:
    build:
      context: .
      args:
        COMMIT_REF: 51.0.1
        BUILD_DATE: "12.12.12"
    container_name: feed-app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - SERVER=mongodb
      - DB=article
      - ARTICLE_COLLECTION=articles
      - DB_USER=article_user
      - DB_PASSWORD=article123
      - AUTH_DB=article
      - DB_SSL=false

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - NODE_ENV=production
      - MONGO_INITDB_ROOT_USERNAME=root_username
      - MONGO_INITDB_ROOT_PASSWORD=very_secure_root_pass
    volumes:
      - ./data/db:/data/db
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    ports:
        - 27017:27017
