version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_IMAGE_URL:$CIRCLE_BUILD_NUM .
      - run: docker push $DOCKER_IMAGE_URL:$CIRCLE_BUILD_NUM
  test:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/tommbee/go-article-feed
    steps:
      - checkout
      - run: go get
      - run: go test
  deploy:
    machine: true
    steps:
      - checkout
      - run: ./deployment/deploy.sh
workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: master
      - test:
          requires:
            - build
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
